imports:
  - { resource: config.prod.yml }

parameters:
  paste.ttl: 3600

framework:
  router:
    resource: '%kernel.root_dir%/../cfg/routing.dev.yml'
    strict_requirements: true
  session:
    cookie_secure: false
  profiler: { only_exceptions: false }

web_profiler:
  toolbar: true
  intercept_redirects: false

monolog:
  handlers:
    main:
      type: 'stream'
      path: '%kernel.logs_dir%/%kernel.name%.log'
      level: 'debug'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Doctrine\Common\Cache\FilesystemCache:
    arguments: ['%kernel.cache_dir%/data']

  Doctrine\Common\Cache\Cache:
    alias: 'Doctrine\Common\Cache\FilesystemCache'
