imports:
  - { resource: config.prod.yml }

framework:
  router:
    resource: '%kernel.root_dir%/../cfg/routing.dev.yml'
    strict_requirements: true
  profiler: { only_exceptions: false }

web_profiler:
  toolbar: true
  intercept_redirects: false

parameters:
  paste.ttl: 3600

monolog:
  handlers:
    main:
      type: 'stream'
      path: '%kernel.logs_dir%/%kernel.name%.log'
      level: 'debug'

services:
  paste.cache:
    class: 'Doctrine\Common\Cache\FilesystemCache'
    arguments: [ '%kernel.cache_dir%/data' ]
