imports:
  - { resource: config.dev.yml }

parameters:
  paste.ttl: 60

framework:
  test: ~
  profiler:
    collect: false

web_profiler:
  toolbar: false

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Doctrine\Common\Cache\ArrayCache: ~

  Doctrine\Common\Cache\Cache:
    alias: 'Doctrine\Common\Cache\ArrayCache'

