language: php

branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.composer/cache/files"

branches:
  only:
    - master

git:
  depth: 10

sudo: false

services:
  - redis-server

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: nightly
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader

script:
  - vendor/bin/phpunit
