sudo: false
dist: trusty
language: php

addons:
  apt:
    packages:
      - parallel

git:
  depth: 10

branches:
  only:
    - master

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: nightly
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - echo memory_limit = -1 >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader

script:
  - vendor/bin/phpunit

cache:
  directories:
    - "$HOME/.composer/cache/files"
    - "vendor"
