language: php

env:
  secure: "AgSRwP3OD/NDYv1l8IWXvKcVs2HFMW31zpL847Y0E59BkFsHrE6GWnOlJedUhMrcw6rw9OnWejc6YOypLZb8TUt2zJtj9k4xbucQmRZRQkF6cYXfcvKNmJqV0Glmdk/A9FmLhXl9kcWlsVNDDcQWYdLxNGYZeNkn7fwzbu8ycfE="

cache:
  directories:
    - $HOME/.composer/cache

git:
  depth: 10

services:
  - redis-server

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

before_install:
  - composer config --global github-oauth.github.com $GITHUB_TRAVIS_TOKEN
  - composer self-update --clean-backups --no-interaction

install:
  - composer install --prefer-dist --optimize-autoloader --no-interaction --profile -v

script:
  - vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover var/build/clover.xml
