language: php

env:
  secure: Zv6RzErMo6OCpcYb6dm+aWLUXjAlLGiYuiy/sVui/neOpFXwIrr06LI7XPp1FM0YnQx/zGb9ibHtJEviciZcA0Yn/rhrfnbYPH2LbPEUDe/gWmKtu2aHpg4bB5yPSys57xfxAEs/3pfdKgCcrg6BmtEhleuIY59t4Q1PUtsjzYE=

cache:
  directories:
    - $HOME/.composer/cache

git:
  depth: 10

services:
  - redis-server

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

before_install:
  - composer config --global github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer self-update --clean-backups --no-interaction

install:
  - composer install --prefer-dist --optimize-autoloader --no-interaction --profile -v

script:
  - vendor/bin/phpunit -c phpunit.all.xml
