language: php

services:
  - redis-server

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - cp .env.example .env
  - composer self-update -n
  - composer install -o -n

script:
  - composer checkstyle
  - composer test-all
