dist: trusty

git:
  depth: 10

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.23.1
    - DOCKER_COMPOSE_RELEASE="https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)"

cache:
  directories:
    - "$HOME/.composer"
    - "vendor"

before_install:
  # upgrade docker
  - docker --version
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version
  # install a recent docker-compose version
  - docker-compose --version
  - sudo curl --silent --fail --retry 3 --location --output /usr/local/bin/docker-compose --url $DOCKER_COMPOSE_RELEASE
  - docker-compose --version

before_script:
  - make containers

script:
  - make test

after_script:
  - bash <(curl -s https://codecov.io/bash) -f clover.xml

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
      echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin;
      docker build --file=docker/services/varnish/Dockerfile --tag=alcohol/pastebin-varnish:latest .;
      docker build --file=docker/services/nginx/Dockerfile --tag=alcohol/pastebin-nginx:latest .;
      docker build --file=docker/services/php-fpm/Dockerfile.dist --tag=alcohol/pastebin-fpm:latest --build-arg=RELEASE=$(git rev-parse --short $TRAVIS_COMMIT) .;
      docker push alcohol/pastebin-varnish:latest;
      docker push alcohol/pastebin-nginx:latest;
      docker push alcohol/pastebin-fpm:latest;
      docker logout;
    fi

