language: php

env:
  secure: "AgSRwP3OD/NDYv1l8IWXvKcVs2HFMW31zpL847Y0E59BkFsHrE6GWnOlJedUhMrcw6rw9OnWejc6YOypLZb8TUt2zJtj9k4xbucQmRZRQkF6cYXfcvKNmJqV0Glmdk/A9FmLhXl9kcWlsVNDDcQWYdLxNGYZeNkn7fwzbu8ycfE="

cache:
  directories:
    - "$HOME/.composer/cache/files"
    - "$HOME/.php-cs-fixer"

git:
  depth: 10

sudo: false

php:
  - 5.5
  - 5.6
  - 7
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - composer self-update --no-interaction --no-progress
  - composer config --no-interaction --global github-oauth.github.com $GITHUB_TRAVIS_TOKEN

install:
  - composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"

script:
  - vendor/bin/phpunit
  - vendor/bin/php-cs-fixer fix --cache-file "$HOME/.php-cs-fixer/.php_cs.cache" --dry-run --diff --verbose
