language: php

cache:
  directories:
    - $HOME/.composer/cache

services:
  - redis-server

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7
  fast_finish: true

before_script:
  - composer self-update --clean-backups --no-interaction
  - composer install -vvv --profile --prefer-dist --optimize-autoloader --no-interaction

script:
  - vendor/bin/phpunit -c tst/phpunit.xml
