version: '3.3'

services:

  nginx:
    build:
      context: .
      dockerfile: docker/services/nginx/Dockerfile
    container_name: paste.robbast.nl-nginx
    cap_drop:
      - ALL
    labels:
      traefik.frontend.rule: "Host:pastebin.docker.localhost"
    links:
      - php
      - php:fcgi
    networks:
      - pastebin-internal
      - traefik

  php:
    build:
      context: .
      dockerfile: docker/services/php-fpm/Dockerfile
    container_name: paste.robbast.nl-fpm
    cap_drop:
      - ALL
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_SECRET=not-so-secret
    working_dir: /srv
    volumes:
      - .:/srv
    networks:
      - pastebin-internal

networks:
  pastebin-internal:
    internal: true
  traefik:
    external: true
