version: '3.3'

services:

  php:
    build:
      context: .
      dockerfile: docker/services/php-fpm/Dockerfile
    container_name: pastebin-fpm
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_SECRET=not-so-secret
    working_dir: /srv
    volumes:
      - .:/srv
    networks:
      default:
        aliases:
          - fcgi

  nginx:
    build:
      context: .
      dockerfile: docker/services/nginx/Dockerfile
    container_name: pastebin-nginx
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_webgateway
      traefik.backend: pastebin
      traefik.frontend.rule: "Host:pastebin.localhost"
      traefik.port: 8000
    links:
      - php
      - php:fcgi
    networks:
      - traefik_webgateway
      - default

networks:

  default:

  traefik_webgateway:
    external: true
