version: '3.6'

services:

  proxy:
    image: traefik
    container_name: traefik-proxy
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/traefik/traefik.toml:/traefik.toml:ro
      - /etc/traefik/acme.json:/acme.json
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

  pastebin-nginx:
    image: alcohol/pastebin-nginx:latest
    container_name: paste.robbast.nl-nginx
    restart: unless-stopped
    read_only: true
    labels:
      traefik.docker.network: "traefik"
    networks:
      - pastebin-internal
      - traefik
    expose:
      - "8000"
    tmpfs:
      - /tmp:uid=100
      - /run:uid=100
      - /var/cache/nginx:uid=100
    cap_drop:
      - ALL
    depends_on:
      - pastebin-fpm

  pastebin-fpm:
    image: alcohol/pastebin-fpm:latest
    container_name: paste.robbast.nl-fpm
    restart: unless-stopped
    read_only: true
    networks:
      pastebin-internal:
        aliases:
          - fcgi
    expose:
      - "9000"
    env_file:
      - .env
    tmpfs:
      - /tmp:uid=82
      - /srv/var:uid=82
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
    depends_on:
      - pastebin-redis

  pastebin-redis:
    image: redis:4-alpine
    container_name: paste.robbast.nl-redis
    restart: unless-stopped
    read_only: true
    command: "redis-server --appendonly yes"
    networks:
      pastebin-internal:
        aliases:
          - redis
    expose:
      - "6379"
    tmpfs:
      - /tmp
    volumes:
      - "pastebin-redisdata:/data"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    sysctls:
      net.core.somaxconn: 1024

networks:

  traefik:
    external: true

  pastebin-internal:
    internal: true

volumes:

  pastebin-redisdata:
