version: '3.3'

services:

  php:
    build:
      context: .
      dockerfile: docker/services/php-fpm/Dockerfile
    container_name: paste.robbast.nl-fpm
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_SECRET=not-so-secret
    working_dir: /srv
    volumes:
      - .:/srv
    networks:
      pastebin-internal:
        aliases:
          - fcgi

  nginx:
    build:
      context: .
      dockerfile: docker/services/nginx/Dockerfile
    container_name: paste.robbast.nl-nginx
    ports:
      - "8000:8000"
    links:
      - php
      - php:fcgi
    networks:
      - default
      - pastebin-internal

networks:

  default:

  internal:
    internal: true
