version: '3.3'

services:

  nginx:
    build:
      context: .
      dockerfile: docker/services/nginx/Dockerfile
    container_name: paste.robbast.nl-nginx
    cap_drop:
      - ALL
    ports:
      - "8000:8000"
    links:
      - php
      - php:fcgi
    networks:
      - default
      - pastebin-internal

  php:
    build:
      context: .
      dockerfile: docker/services/php-fpm/Dockerfile
    container_name: paste.robbast.nl-fpm
    cap_drop:
      - ALL
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_SECRET=not-so-secret
    working_dir: /srv
    volumes:
      - .:/srv
    networks:
      - pastebin-internal

networks:
  default:
  pastebin-internal:
    internal: true
