version: '3.7'

services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: phpbin-nginx
    labels:
    - traefik.enable=true
    - traefik.http.routers.phpbin.rule=Host(`phpbin.localhost`)
    volumes:
    - ./public:/srv/public
    expose:
    - 8000
    depends_on:
    - fpm
    networks:
      traefik:
      phpbin:
        aliases:
        - nginx
    cap_drop:
    - ALL
    healthcheck:
      test: nc -z localhost 8000
      interval: 5s

  fpm:
    build:
      context: .
      dockerfile: docker/fpm/Dockerfile
    container_name: phpbin-fpm
    user: $DOCKER_UID:$DOCKER_GID
    environment:
    - APP_ENV=dev
    - APP_DEBUG=1
    - APP_SECRET=not-so-secret
    working_dir: /srv
    volumes:
    - .:/srv
    tmpfs:
    - /tmp
    depends_on:
    - redis
    networks:
      phpbin:
        aliases:
          - fcgi
    cap_drop:
    - ALL
    cap_add:
    - SETUID
    - SETGID
    - DAC_OVERRIDE
    healthcheck:
      test: nc -z localhost 9000
      interval: 5s

  redis:
    image: redis:5-alpine
    container_name: phpbin-redis
    read_only: true
    command: "redis-server --appendonly yes"
    networks:
    - phpbin
    tmpfs:
    - /tmp
    volumes:
    - "phpbin-redis:/data"
    cap_drop:
    - ALL
    cap_add:
    - CHOWN
    - SETGID
    - SETUID
    sysctls:
      net.core.somaxconn: 1024
    healthcheck:
      test: nc -z localhost 6379
      interval: 5s

networks:

  phpbin:

  traefik:
    external: true

volumes:

  phpbin-redis:
