version: '3.7'

services:

  varnish:
    build:
      context: .
      dockerfile: docker/services/varnish/Dockerfile
    container_name: pastebin-varnish
    labels:
      traefik.backend: pastebin-varnish
      traefik.frontend.rule: "Host:cache.pastebin.localhost"
      traefik.port: 6081
    tmpfs:
      - /var/lib/varnish:exec
    depends_on:
      - nginx
    networks:
      traefik:
      default:
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - DAC_OVERRIDE

  nginx:
    build:
      context: .
      dockerfile: docker/services/nginx/Dockerfile
    container_name: pastebin-nginx
    labels:
      traefik.backend: pastebin-nginx
      traefik.frontend.rule: "Host:pastebin.localhost"
      traefik.port: 8000
    volumes:
      - ./public:/srv/public
    depends_on:
      - php-fpm
    networks:
      traefik:
      default:
        aliases:
          - nginx
    cap_drop:
      - ALL

  php-fpm:
    build:
      context: .
      dockerfile: docker/services/php-fpm/Dockerfile
    container_name: pastebin-fpm
    user: $DOCKER_UID:$DOCKER_GID
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_SECRET=not-so-secret
    working_dir: /srv
    volumes:
      - .:/srv
    tmpfs:
      - /tmp
    depends_on:
      - redis
    networks:
      default:
        aliases:
          - fcgi
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - DAC_OVERRIDE

  redis:
    image: redis:5.0-alpine
    container_name: pastebin-redis
    read_only: true
    command: "redis-server --appendonly yes"
    networks:
      - default
    tmpfs:
      - /tmp
    volumes:
      - "pastebin-redisdata:/data"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    sysctls:
      net.core.somaxconn: 1024

networks:

  default:

  traefik:
    external: true

volumes:

  pastebin-redisdata:
