framework:
  secret: %secret%
  http_method_override: true
  router:
    resource: '%kernel.root_dir%/config/%kernel.environment%.routing.yml'
    strict_requirements: %kernel.debug%

parameters:
  paste.ttl: 86400 # 1 day
  redis.scheme: tcp
  redis.host: localhost
  redis.port: 6379

imports:
  - { resource: services.yml }
