framework:
  secret: %secret%
  http_method_override: true
  router:
    resource: '%kernel.root_dir%/config/%kernel.environment%/routing.yml'
    strict_requirements: %kernel.debug%

monolog:
  handlers:
    main:
      type: fingers_crossed
      action_level: %monolog_action_level%
      handler: nested
    nested:
      type: stream
      path: '%kernel.logs_dir%/%kernel.name%.log'
      level: debug

imports:
  - { resource: services.yml }
