paste.index:
  path: /
  methods: [GET]
  defaults: { _controller: 'paste.controller:indexAction' }

paste.create:
  path: /
  methods: [PUT,POST]
  defaults: { _controller: 'paste.controller:createAction' }

paste.read:
  path: /{code}
  methods: [GET]
  defaults: { _controller: 'paste.controller:readAction' }

paste.update:
  path: /{code}
  methods: [PUT,PATCH,POST]
  defaults: { _controller: 'paste.controller:updateAction' }

paste.delete:
  path: /{code}
  methods: [DELETE]
  defaults: { _controller: 'paste.controller:deleteAction' }
