imports:
  - { resource: config.prod.yml }

parameters:
  paste.ttl: 3600

monolog:
  handlers:
    main:
      type: 'stream'
      path: '%kernel.logs_dir%/%kernel.name%.log'
      level: 'debug'

services:
  paste.cache:
    class: 'Doctrine\Common\Cache\FilesystemCache'
    arguments: [ '%kernel.cache_dir%/data' ]
