framework:
  secret: '%secret%'
  http_method_override: true
  router:
    resource: '%kernel.root_dir%/config/routing/routing.%kernel.environment%.yml'
    strict_requirements: %kernel.debug%

parameters:
  paste.ttl: 86400 # 1 day
  redis.scheme: tcp
  redis.host: localhost
  redis.port: 6379

services:

  predis.client:
    class: Predis\Client
    arguments:
      -
        scheme: %redis.scheme%
        host: %redis.host%
        port: %redis.port%

  paste.hashutils:
    class: Alcohol\Paste\Util\HashUtils

  paste.manager:
    class: Alcohol\Paste\Entity\PasteManager
    arguments: [ @predis.client, @paste.hashutils, %paste.ttl% ]

  paste.controller.index:
    class: Alcohol\Paste\Controller\IndexController
    arguments: [ @router ]

  paste.controller.create:
    class: Alcohol\Paste\Controller\CreateController
    arguments: [ @paste.manager, @router ]

  paste.controller.read:
    class: Alcohol\Paste\Controller\ReadController
    arguments: [ @paste.manager ]

  paste.controller.update:
    class: Alcohol\Paste\Controller\UpdateController
    arguments: [ @paste.manager ]

  paste.controller.delete:
    class: Alcohol\Paste\Controller\DeleteController
    arguments: [ @paste.manager ]

  paste.kernel.exception_listener:
    class: Alcohol\Paste\EventListener\ExceptionListener
    arguments: [ @logger ]
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

  paste.command.read:
    class: Alcohol\Paste\Console\Command\ReadCommand
    arguments: [ @paste.manager ]
    tags:
      - { name: console.command }

  paste.command.count:
    class: Alcohol\Paste\Console\Command\CountCommand
    arguments: [ @paste.manager ]
    tags:
      - { name: console.command }

  paste.command.list:
    class: Alcohol\Paste\Console\Command\ListCommand
    arguments: [ @paste.manager ]
    tags:
      - { name: console.command }

  paste.command.delete:
    class: Alcohol\Paste\Console\Command\DeleteCommand
    arguments: [ @paste.manager ]
    tags:
      - { name: console.command }
