imports:
  - { resource: config.dev.yml }

parameters:
  paste.ttl: 60

framework:
  test: ~
  session:
    storage_id: session.storage.mock_file
  profiler:
    collect: false
  router:
    resource: '%kernel.root_dir%/config/routing.test.yml'

web_profiler:
  toolbar: false

services:
  paste.cache:
    class: 'Doctrine\Common\Cache\ArrayCache'
