# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  paste.ttl: 2592000
  redis.scheme: 'tcp'
  redis.host: 'redis'
  redis.port: 6379

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false       # Allows optimizing the container by removing unused services; this also means
                        # fetching services directly from the container via $container->get() won't work.
                        # The best practice is to be explicit about your dependencies anyway.

  Paste\:
    resource: '../src/*'
    exclude: '../src/{Controller,Entity,Exception,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  Paste\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  Predis\Client:
    arguments:
      -
        scheme: '%redis.scheme%'
        host: '%redis.host%'
        port: '%redis.port%'
        timeout: 1
        read_write_timeout: 2
        tcp_nodelay: true

  Predis\ClientInterface: '@Predis\Client'

  Doctrine\Common\Cache\PredisCache: ~

  Doctrine\Common\Cache\Cache: '@Doctrine\Common\Cache\PredisCache'

  Paste\Security\HashGenerator:
    arguments:
      $secret: '%kernel.secret%'

  Paste\Repository\PasteRepository:
    arguments:
      $default_ttl: '%paste.ttl%'
